sudo: false
language: python

cache:
  directories:
    - $HOME/env

before_install:
  - pip install hererocks
  - hererocks $HOME/env --luajit 2.0.4 --luarocks latest
  - source $HOME/env/bin/activate
  - git clone https://github.com/impulsh/gluacheck $HOME/gluacheck

install:
  - luarocks install ldoc
  - luarocks install luasrcdiet
  - cd $HOME/gluacheck
  - luarocks make
  - cd $TRAVIS_BUILD_DIR

script:
  - ldoc . --fatalwarnings
  - luacheck .
  - bash scripts/deploy.sh


deploy:
  - provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
  - provider: releases
  api_key:
    secure: TEST
